name: Build and Push Docker Image

on:
  push:
    branches: main
jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stadtulm/ixsi-gbfs-converter:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
